apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  labels:
    app: springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        # image: tushardashpute/springboohello:5
        image: REPLACE_IMAGE   # 🔁 Placeholder for Jenkins to replace
        imagePullPolicy: Always
        ports:
        - containerPort: 33333
